// <auto-generated />
using System;
using Katino.Infrastructure.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Katino.Infrastructure.Migrations
{
    [DbContext(typeof(KatinoDbContext))]
    [Migration("20260711205208_ProductVariantRedistributionHistoryUpdatesToConsiderPendingReturns")]
    partial class ProductVariantRedistributionHistoryUpdatesToConsiderPendingReturns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Katino.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RegistryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Katino.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("HexCode")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Katino.Domain.Entities.CrmUserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NpCityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NpWarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("NpCityId");

                    b.HasIndex("NpWarehouseId");

                    b.ToTable("CrmUserSettings");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Katino.Domain.Entities.DiscountBundleProduct", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("DiscountId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DiscountBundleProducts");
                });

            modelBuilder.Entity("Katino.Domain.Entities.DiscountCollection", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("char(36)");

                    b.HasKey("DiscountId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("DiscountCollections");
                });

            modelBuilder.Entity("Katino.Domain.Entities.DiscountProduct", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("DiscountId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DiscountProducts");
                });

            modelBuilder.Entity("Katino.Domain.Entities.FinanceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type", "IsActive");

                    b.ToTable("FinanceCategories");
                });

            modelBuilder.Entity("Katino.Domain.Entities.FinanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InternetDocumentIntDocNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReversedEntryId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("SaleType")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EntryDate");

                    b.HasIndex("OrderId");

                    b.HasIndex("ReversedEntryId");

                    b.HasIndex("CategoryId", "EntryDate");

                    b.ToTable("FinanceEntries");
                });

            modelBuilder.Entity("Katino.Domain.Entities.MeasurementType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MeasurementTypes");
                });

            modelBuilder.Entity("Katino.Domain.Entities.NovaPoshtaSyncStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ApiRequestedRecords")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DbInsertedRecords")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SyncType")
                        .HasColumnType("int");

                    b.Property<Guid>("TriggeredBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("NovaPoshtaSyncStatuses");
                });

            modelBuilder.Entity("Katino.Domain.Entities.NpCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DeliveryCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Present")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NpCities");
                });

            modelBuilder.Entity("Katino.Domain.Entities.NpContactPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CounterpartyRef")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Phones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NpContactPersons");
                });

            modelBuilder.Entity("Katino.Domain.Entities.NpOptionsSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("VolumetricHeight")
                        .HasColumnType("double");

                    b.Property<double>("VolumetricLength")
                        .HasColumnType("double");

                    b.Property<double>("VolumetricWidth")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("NpOptionsSeats");
                });

            modelBuilder.Entity("Katino.Domain.Entities.NpWarehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CityRef")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ShortAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WarehouseIndex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CityRef");

                    b.HasIndex("Description");

                    b.HasIndex("Ref")
                        .IsUnique();

                    b.ToTable("NpWarehouses");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double?>("AfterpaymentOnGoodsCost")
                        .HasColumnType("double");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreationDateTimeSystem")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("GeneralOrderInfo")
                        .HasColumnType("longtext");

                    b.Property<bool>("InternetDocumentCreationAttempted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InternetDocumentIntDocNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("InternetDocumentRef")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderInternetDocStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderRecipientId")
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PayerType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecipientNpCityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RecipientNpWarehouseId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SaleType")
                        .HasColumnType("int");

                    b.Property<int>("SeatsAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendUntilDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SenderContactPersonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SenderNpCityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SenderNpWarehouseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UpdateReasonDetails")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("OrderRecipientId");

                    b.HasIndex("RecipientNpCityId");

                    b.HasIndex("RecipientNpWarehouseId");

                    b.HasIndex("SenderContactPersonId");

                    b.HasIndex("SenderNpCityId");

                    b.HasIndex("SenderNpWarehouseId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderAddressInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RecipientAddressName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipientAddressNote")
                        .HasColumnType("longtext");

                    b.Property<string>("RecipientCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipientFlat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecipientHouse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderAddressInfo");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCustomTailoring")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderItemStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToProduce")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderNpOptionsSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NpOptionsSeatId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NpOptionsSeatId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderNpOptionsSeats");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderOrderTag", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderTagId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderId", "OrderTagId");

                    b.HasIndex("OrderTagId");

                    b.ToTable("OrderOrderTags");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid>("NpContactPersonId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NpContactPersonId")
                        .IsUnique();

                    b.ToTable("OrderRecipients");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanBeDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("OrderTags");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DropPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("WholesalePrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductCollection", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("CollectionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCollections");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductPhotos");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDrop")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("QuantityDropSold")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRegularSold")
                        .HasColumnType("int");

                    b.Property<int>("SewingQueueVisibility")
                        .HasColumnType("int");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariantMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MeasurementTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementTypeId");

                    b.HasIndex("ProductVariantId", "MeasurementTypeId")
                        .IsUnique();

                    b.ToTable("ProductVariantMeasurements");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariantRedistributionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPendingPhysicalArrival")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceOrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourceOrderItemId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SourceOrderTtnSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("TargetOrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TargetOrderItemId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("SourceOrderId");

                    b.HasIndex("TargetOrderId");

                    b.ToTable("ProductVariantRedistributionHistory");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariantSewer", b =>
                {
                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SewerId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductVariantId", "SewerId");

                    b.HasIndex("SewerId");

                    b.ToTable("ProductVariantSewers");
                });

            modelBuilder.Entity("Katino.Domain.Entities.SewingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCustomTailoring")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SewedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("SewedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SewedQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("SewedBy");

                    b.ToTable("SewingHistory");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("Katino.Domain.Entities.TelegramChatConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ChatName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("TelegramSettingsId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramSettingsId");

                    b.ToTable("TelegramChatConfigs");
                });

            modelBuilder.Entity("Katino.Domain.Entities.TelegramSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BotToken")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.ToTable("TelegramSettings");
                });

            modelBuilder.Entity("Katino.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Katino.Domain.Entities.CrmUserSettings", b =>
                {
                    b.HasOne("Katino.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Settings")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.NpCity", "NpCity")
                        .WithMany()
                        .HasForeignKey("NpCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.NpWarehouse", "NpWarehouse")
                        .WithMany()
                        .HasForeignKey("NpWarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("NpCity");

                    b.Navigation("NpWarehouse");
                });

            modelBuilder.Entity("Katino.Domain.Entities.DiscountBundleProduct", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Discount", "Discount")
                        .WithMany("BundleProducts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Katino.Domain.Entities.DiscountCollection", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Discount", "Discount")
                        .WithMany("DiscountCollections")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("Katino.Domain.Entities.DiscountProduct", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Discount", "Discount")
                        .WithMany("DiscountProducts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Katino.Domain.Entities.FinanceEntry", b =>
                {
                    b.HasOne("Katino.Domain.Entities.FinanceCategory", "Category")
                        .WithMany("Entries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Katino.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Katino.Domain.Entities.FinanceEntry", "ReversedEntry")
                        .WithMany()
                        .HasForeignKey("ReversedEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Order");

                    b.Navigation("ReversedEntry");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Order", b =>
                {
                    b.HasOne("Katino.Domain.Entities.OrderRecipient", "OrderRecipient")
                        .WithMany("Orders")
                        .HasForeignKey("OrderRecipientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Katino.Domain.Entities.NpCity", "RecipientNpCity")
                        .WithMany()
                        .HasForeignKey("RecipientNpCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Katino.Domain.Entities.NpWarehouse", "RecipientNpWarehouse")
                        .WithMany()
                        .HasForeignKey("RecipientNpWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Katino.Domain.Entities.NpContactPerson", "SenderContactPerson")
                        .WithMany("Orders")
                        .HasForeignKey("SenderContactPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.NpCity", "SenderNpCity")
                        .WithMany()
                        .HasForeignKey("SenderNpCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.NpWarehouse", "SenderNpWarehouse")
                        .WithMany()
                        .HasForeignKey("SenderNpWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderRecipient");

                    b.Navigation("RecipientNpCity");

                    b.Navigation("RecipientNpWarehouse");

                    b.Navigation("SenderContactPerson");

                    b.Navigation("SenderNpCity");

                    b.Navigation("SenderNpWarehouse");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderAddressInfo", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Order", null)
                        .WithOne("AddressInfo")
                        .HasForeignKey("Katino.Domain.Entities.OrderAddressInfo", "Id");

                    b.HasOne("Katino.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderNpOptionsSeat", b =>
                {
                    b.HasOne("Katino.Domain.Entities.NpOptionsSeat", "NpOptionsSeat")
                        .WithMany("OrderNpOptionsSeats")
                        .HasForeignKey("NpOptionsSeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Order", "Order")
                        .WithMany("OrderNpOptionsSeats")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpOptionsSeat");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderOrderTag", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Order", "Order")
                        .WithMany("OrderTags")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.OrderTag", "OrderTag")
                        .WithMany("OrderOrderTags")
                        .HasForeignKey("OrderTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderTag");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderRecipient", b =>
                {
                    b.HasOne("Katino.Domain.Entities.NpContactPerson", "NpContactPerson")
                        .WithOne()
                        .HasForeignKey("Katino.Domain.Entities.OrderRecipient", "NpContactPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpContactPerson");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Product", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductCollection", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Collection", "Collection")
                        .WithMany("ProductCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Product", "Product")
                        .WithMany("ProductCollections")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductPhoto", b =>
                {
                    b.HasOne("Katino.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("Photos")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Katino.Domain.Entities.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariantMeasurement", b =>
                {
                    b.HasOne("Katino.Domain.Entities.MeasurementType", "MeasurementType")
                        .WithMany("Measurements")
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("Measurements")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementType");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariantRedistributionHistory", b =>
                {
                    b.HasOne("Katino.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.Order", "SourceOrder")
                        .WithMany()
                        .HasForeignKey("SourceOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Katino.Domain.Entities.Order", "TargetOrder")
                        .WithMany()
                        .HasForeignKey("TargetOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductVariant");

                    b.Navigation("SourceOrder");

                    b.Navigation("TargetOrder");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariantSewer", b =>
                {
                    b.HasOne("Katino.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("Sewers")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.AppUser", "Sewer")
                        .WithMany()
                        .HasForeignKey("SewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("Sewer");
                });

            modelBuilder.Entity("Katino.Domain.Entities.SewingHistory", b =>
                {
                    b.HasOne("Katino.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.AppUser", "SewedByUser")
                        .WithMany()
                        .HasForeignKey("SewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("SewedByUser");
                });

            modelBuilder.Entity("Katino.Domain.Entities.TelegramChatConfig", b =>
                {
                    b.HasOne("Katino.Domain.Entities.TelegramSettings", "TelegramSettings")
                        .WithMany("ChatConfigs")
                        .HasForeignKey("TelegramSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Katino.Domain.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Katino.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Katino.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Katino.Domain.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Katino.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Katino.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Katino.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Collection", b =>
                {
                    b.Navigation("ProductCollections");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Color", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Discount", b =>
                {
                    b.Navigation("BundleProducts");

                    b.Navigation("DiscountCollections");

                    b.Navigation("DiscountProducts");
                });

            modelBuilder.Entity("Katino.Domain.Entities.FinanceCategory", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Katino.Domain.Entities.MeasurementType", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("Katino.Domain.Entities.NpContactPerson", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Katino.Domain.Entities.NpOptionsSeat", b =>
                {
                    b.Navigation("OrderNpOptionsSeats");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Order", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderNpOptionsSeats");

                    b.Navigation("OrderTags");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderRecipient", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Katino.Domain.Entities.OrderTag", b =>
                {
                    b.Navigation("OrderOrderTags");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductCollections");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Katino.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("OrderItems");

                    b.Navigation("Photos");

                    b.Navigation("Sewers");
                });

            modelBuilder.Entity("Katino.Domain.Entities.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Katino.Domain.Entities.TelegramSettings", b =>
                {
                    b.Navigation("ChatConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
